# Generated by Django 4.2 on 2023-06-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savdo_turi', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=223, null=True)),
                ('chegirma_turi', models.CharField(choices=[('Chegirmaviy_summa', 'Chegirmaviy_summa'), ('Chegirma_narx', 'Chegirma_narx')], default='Chegirmaviy_summa', max_length=223, null=True)),
                ('vaqt', models.DateTimeField()),
                ('chegirma', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Savdo',
                'verbose_name_plural': 'Savdolar',
            },
        ),
        migrations.CreateModel(
            name='SavdoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.FloatField(default=0)),
                ('narx_turi', models.CharField(choices=[('Narxida', 'Narxida'), ('Chegirma', 'Chegirma')], default='Chegirma', max_length=223, null=True)),
                ('narx', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sotish_turi', models.CharField(choices=[("O'lchovli", "O'lchovli"), ("O'lchovsiz", "O'lchovsiz")], default="O'lchovli Savdo", max_length=223, null=True)),
                ('sotish_olchov', models.CharField(blank=True, max_length=9000, null=True)),
                ('total_summa', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tranzaksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('turi', models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim')], max_length=200)),
                ('status', models.CharField(choices=[('mijoz', 'mijoz'), ('mahsulot', 'mahsulot'), ('hodim', 'hodim'), ('boshqa', 'Boshqa')], max_length=200)),
            ],
            options={
                'verbose_name': 'Tranzaksiya turi',
                'verbose_name_plural': 'Tranzaksiya turi',
            },
        ),
        migrations.CreateModel(
            name='Tolovlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolov_turi', models.CharField(choices=[('naqt', 'Naqt'), ('plastik', 'Plastik'), ('kochirma', "Ko'chirma"), ('boshqa', 'Boshqa')], max_length=200)),
                ('muddat', models.DateTimeField(blank=True, null=True)),
                ('summa', models.FloatField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('yaralgan_sana', models.DateTimeField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('savdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar_mijozlar', to='savdo.savdo')),
                ('tranzaksiya_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savdo.tranzaksiya')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['summa'],
            },
        ),
    ]
