# Generated by Django 4.2 on 2023-06-04 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('savdo', '0001_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tolovlar',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Sotuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sotgan'),
        ),
        migrations.AddField(
            model_name='savdoproduct',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahsulotlar', to='products.mahsulotlar'),
        ),
        migrations.AddField(
            model_name='savdoproduct',
            name='olchov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mahsulot_olchov'),
        ),
        migrations.AddField(
            model_name='savdoproduct',
            name='savdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savdo_products', to='savdo.savdo'),
        ),
        migrations.AddField(
            model_name='savdo',
            name='mijoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savdolar', to='users.mijoz'),
        ),
        migrations.AddField(
            model_name='savdo',
            name='user',
            field=models.ForeignKey(help_text='Sotuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sotgan'),
        ),
        migrations.AlterUniqueTogether(
            name='tolovlar',
            unique_together={('savdo', 'summa')},
        ),
    ]
