# Generated by Django 4.2 on 2023-06-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savdo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolovlar',
            name='yaralgan_sana',
            field=models.DateTimeField(null=True),
        ),
    ]
