# Generated by Django 4.2 on 2023-06-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moliya_chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, default=None, help_text='svetga,arendaga ...', max_length=200, null=True)),
                ('tolov_turi', models.CharField(blank=True, choices=[('naqt', 'Naqt'), ('plastik', 'Plastik'), ('kochirma', "Ko'chirma"), ('boshqa', 'Boshqa')], max_length=200, null=True)),
                ('vaqt', models.DateTimeField()),
                ('summa', models.PositiveIntegerField(blank=True, null=True)),
                ('ombor_id', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Moliya chiqim',
                'verbose_name_plural': 'Moliya chiqim',
            },
        ),
        migrations.CreateModel(
            name='OmborCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriya', models.CharField(max_length=223)),
            ],
            options={
                'verbose_name': 'Ombor Kategoriyasi',
                'verbose_name_plural': 'Ombor Kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Omborxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savdo_turi', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=223, null=True)),
                ('miqdor', models.FloatField()),
                ('narx_turi', models.CharField(choices=[('Narxli', 'Narxli'), ('Umumiy narx', 'Umumiy narx')], default='Narxli', max_length=223, null=True)),
                ('narx', models.FloatField(blank=True, default=0, null=True)),
                ('total_summa', models.PositiveIntegerField(default=0)),
                ('vaqt', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('chiqim_id', models.FloatField(blank=True, null=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategoriya_ombor', to='moliya.omborcategory')),
            ],
            options={
                'verbose_name': 'Omborxona',
                'verbose_name_plural': 'Omborxona',
            },
        ),
    ]
