# Generated by Django 4.2 on 2023-06-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moliya', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omborxona',
            name='mahsulot_nomi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ombor_mahsulot', to='products.mahsulotlar'),
        ),
        migrations.AddField(
            model_name='omborxona',
            name='olchov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ombor_olchovi', to='products.mahsulot_olchov'),
        ),
    ]
