# Generated by Django 4.2 on 2023-06-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('moliya', '0002_initial'),
        ('savdo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='omborxona',
            name='user',
            field=models.ForeignKey(help_text='Sotuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sotgan'),
        ),
        migrations.AddField(
            model_name='moliya_chiqim',
            name='ishchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ishchi'),
        ),
        migrations.AddField(
            model_name='moliya_chiqim',
            name='mijoz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mijoz'),
        ),
        migrations.AddField(
            model_name='moliya_chiqim',
            name='ombor_savdo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombor_moliya_chiqim', to='moliya.omborxona'),
        ),
        migrations.AddField(
            model_name='moliya_chiqim',
            name='tranzaksiya_turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savdo.tranzaksiya'),
        ),
        migrations.AddField(
            model_name='moliya_chiqim',
            name='user',
            field=models.ForeignKey(help_text='Sotuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sotgan'),
        ),
    ]
