# Generated by Django 4.2 on 2023-06-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        ('moliya', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='omborxona',
            unique_together={('mahsulot', 'olchov')},
        ),
    ]
