# Generated by Django 4.2 on 2023-06-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0004_alter_omborxona_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='omborxona',
            unique_together=set(),
        ),
    ]
