# Generated by Django 4.2 on 2023-06-24 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moliya', '0005_alter_omborxona_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omborxona_Get',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savdo_turi', models.CharField(choices=[('Naqtga', 'Naqtga'), ('Qarzga', 'Qarzga')], default='Naqtga', max_length=223, null=True)),
                ('miqdor', models.FloatField()),
                ('narx_turi', models.CharField(choices=[('Narxli', 'Narxli'), ('Umumiy narx', 'Umumiy narx')], default='Narxli', max_length=223, null=True)),
                ('narx', models.FloatField(blank=True, default=0, null=True)),
                ('total_summa', models.PositiveIntegerField(default=0)),
                ('vaqt', models.DateTimeField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ombor_mahsulotlar', to='products.mahsulotlar')),
                ('olchov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ombor_olchovilar', to='products.mahsulot_olchov')),
                ('user', models.ForeignKey(help_text='Sotuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sotgan')),
            ],
            options={
                'verbose_name': 'Omborxona_Get',
                'verbose_name_plural': 'Omborxona_Get',
            },
        ),
    ]
