# Generated by Django 4.2 on 2023-06-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moliya', '0006_alter_moliya_chiqim_ombor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moliya_chiqim',
            name='ombor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ombor_moliya_chiqim', to='moliya.omborxona'),
        ),
    ]
