# Generated by Django 4.2 on 2023-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analitika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Analitika',
                'verbose_name_plural': 'Analitikalar',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot_olchov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olchov_nomi', models.CharField(max_length=100)),
                ('olchov_format', models.CharField(choices=[('metr', 'metr'), ('kg', 'kg'), ('dona', 'dona'), ('litr', 'litr'), ('tonna', 'tonna'), ('mm', 'mm'), ('sm', 'santimetr'), ('diametr', 'diametr'), ('metr kvadrat', 'metr kvadrat'), ('metr kub', 'metr kub')], max_length=30)),
                ('olchov', models.FloatField(help_text='(kg lik, litrlik ...)')),
                ('narx', models.FloatField()),
            ],
            options={
                'verbose_name': "Mahsulot o'lchovi",
                'verbose_name_plural': "Mahsulot o'lchovlari",
            },
        ),
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=200)),
                ('mahsulot_format', models.CharField(choices=[('metr', 'metr'), ('kg', 'kg'), ('dona', 'dona'), ('litr', 'litr'), ('tonna', 'tonna'), ('mm', 'mm'), ('sm', 'santimetr'), ('diametr', 'diametr'), ('metr kvadrat', 'metr kvadrat'), ('metr kub', 'metr kub')], max_length=30)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, related_name='history_products', to='products.mahsulot_olchov')),
            ],
        ),
    ]
